import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { AuthProvider } from '@/components/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
	<html lang="en">
		<body className={inter.className}>
			<AuthProvider>
				<div className="h-screen flex flex-col justify-between bg-slate-400">
					{/* Upper part of the layout */}
					<div>
						<Header />
						<main className="container mx-auto py-4">
							{children}
						</main>
					</div>

					{/* Lower part of the layout */}
					<div>
						<Footer />
					</div>
				</div>
			</AuthProvider>
		</body>
	</html>
);

export default RootLayout;
